### PR TITLE
WeaveCloud/Cortex integration

### LINKED ISSUE #43: Document Weave Cloud/Cortex integration
Document a prometheus config that:
- Scrapes net/npc metrics from every node in the k8s cluster via discovery
- Forwards metrics to Weave Cloud (see github.com/weaveworks/cortex#getting-started for a relevant YAML fragment)

### PR DESCRIPTION
**Pull request by brb**
This PR adds configurations of headless services used by Prometheus to query `weave-{net/npc}` metrics endpoints.

Relevant Prometheus configurations can be found at https://gist.github.com/brb/435d940a15b4443f5353aa7424ff469e

Fixes #43

### CODE REVIEW

**Comment by brb** [comment]
Keep in mind that the current `weave-net` pod of the `weave-net` daemonset does not expose metrics. For testing purpose, you can use `brb0/weave-{npc,kube}:latest`.

**Comment by brb** [comment]
Updated the gist to include a configmap for queries proposed in https://github.com/weaveworks/service/issues/935

**Comment by awh** [comment]
@brb this PR needs moving to `weaveworks/weave` now - sorry! Continue to reference the issue here for now, until we work out what we're going to do with them in general.

**Comment by brb** [comment]
PR has been moved to https://github.com/weaveworks/weave/pull/2572

**Pull request closed without merging**
